name: 'AutoCoder'
description: 'Generate code snippets from issue descriptions using ChatGPT'
author: "Philipp Kolmann"

inputs:
    GITHUB_TOKEN:
        description: 'GitHub token'
        required: true
        default: ${{ secrets.GITHUB_TOKEN }}
    REPOSITORY:
        description: 'Repository name'
        required: true
        default: ${{ github.repository }}
    ISSUE_NUMBER:
        description: 'Issue number'
        required: true
        default: ${{ github.event.issue.number }}
    OPENAI_API_KEY:
        description: 'OpenAI API key'
        required: true
        default: ${{ secrets.OPENAI_API_KEY }}
    SCRIPT_PATH:
        description: 'Path to the script file'
        required: true
        default: './scripts/script.sh'
    LABEL:
        description: 'Label to trigger the action'
        required: true
        default: 'autocoder-bot'

runs:
    using: 'composite'
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Make script file executable
          run: chmod +x ${{ inputs.SCRIPT_PATH }}

        - name: Generate Code with ChatGPT
          env:
              GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
              REPOSITORY: ${{ inputs.REPOSITORY }}
              ISSUE_NUMBER: ${{ inputs.ISSUE_NUMBER }}
              OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
          run: ${{ inputs.SCRIPT_PATH }} $GITHUB_TOKEN $REPOSITORY $ISSUE_NUMBER $OPENAI_API_KEY

        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v7
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: "Auto-generated code by ChatGPT"
            title: "Auto-generated code by ChatGPT for issue #${{ github.event.issue.number }}"
            body: "This code was generated by ChatGPT based on the issue description."
            branch: "autocoder-branch-${{ github.event.issue.number }}"
            base: "main"
            labels: "autocoder-bot"
            author: "autocoder-bot <actions@github.com>"
            delete-branch: true
