name: "Runs on opened and reopened issues"

on:
  issues:
    types:
      - opened
      - reopened
      - labeled

jobs:
  autoCoder:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Interact with GPT
        uses: "pkolmann/AutoCoder@v1"
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            REPOSITORY: ${{ github.repository }}
            ISSUE_NUMBER: ${{ github.event.issue.number }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            SCRIPT_PATH: './scripts/script.sh'
            LABEL: 'autocoder-bot'